//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPicSorter.Lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_de() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPicSorter.Lang.Lang-de", typeof(Lang_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Außerdem.
        /// </summary>
        internal static string aboutBtn {
            get {
                return ResourceManager.GetString("aboutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Eine benannte Datei.
        /// </summary>
        internal static string aFileNamed {
            get {
                return ResourceManager.GetString("aFileNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à existiert bereits. Möchten Sie es ersetzen? Wählen Sie Nein aus, um beide Dateien beizubehalten..
        /// </summary>
        internal static string alreadyExistsReplaceIt {
            get {
                return ResourceManager.GetString("alreadyExistsReplaceIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Möchten Sie noch vorhandene Dateien ersetzen?.
        /// </summary>
        internal static string alwaysOverwrite {
            get {
                return ResourceManager.GetString("alwaysOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Möchten Sie immer Dateien mit dem gleichen Namen behalten?.
        /// </summary>
        internal static string alwaysRename {
            get {
                return ResourceManager.GetString("alwaysRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à April.
        /// </summary>
        internal static string april {
            get {
                return ResourceManager.GetString("april", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Achtung.
        /// </summary>
        internal static string attention {
            get {
                return ResourceManager.GetString("attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à August.
        /// </summary>
        internal static string august {
            get {
                return ResourceManager.GetString("august", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reise....
        /// </summary>
        internal static string browseBtn {
            get {
                return ResourceManager.GetString("browseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stornieren.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kündigen.
        /// </summary>
        internal static string cancelBtn {
            get {
                return ResourceManager.GetString("cancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stornierung läuft. Bitte warte..
        /// </summary>
        internal static string cancellationInProgress {
            get {
                return ResourceManager.GetString("cancellationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kündigen....
        /// </summary>
        internal static string cancellingBtn {
            get {
                return ResourceManager.GetString("cancellingBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dateien kopieren....
        /// </summary>
        internal static string copyingFiles {
            get {
                return ResourceManager.GetString("copyingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à konnte nicht kopiert werden..
        /// </summary>
        internal static string couldNotBeCopied {
            get {
                return ResourceManager.GetString("couldNotBeCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à konnte nicht ersetzen werden..
        /// </summary>
        internal static string couldNotBeReplaced {
            get {
                return ResourceManager.GetString("couldNotBeReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Datumsformat:.
        /// </summary>
        internal static string dateFormatLbl {
            get {
                return ResourceManager.GetString("dateFormatLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tag.
        /// </summary>
        internal static string dayChk {
            get {
                return ResourceManager.GetString("dayChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dezember.
        /// </summary>
        internal static string december {
            get {
                return ResourceManager.GetString("december", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details:.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suchen Sie beim Sortieren nach Duplikaten.
        /// </summary>
        internal static string duplicateChk {
            get {
                return ResourceManager.GetString("duplicateChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fehler.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bei der Dateisortierung ist ein Fehler aufgetreten..
        /// </summary>
        internal static string errorOccured {
            get {
                return ResourceManager.GetString("errorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Beispiel:.
        /// </summary>
        internal static string exampleLbl {
            get {
                return ResourceManager.GetString("exampleLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Februar.
        /// </summary>
        internal static string february {
            get {
                return ResourceManager.GetString("february", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Datei.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ihre Dateien wurden sortiert..
        /// </summary>
        internal static string fileSorted {
            get {
                return ResourceManager.GetString("fileSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abschluss....
        /// </summary>
        internal static string finalizing {
            get {
                return ResourceManager.GetString("finalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format: numerisch.
        /// </summary>
        internal static string formatNumeralToolStripMenuItem {
            get {
                return ResourceManager.GetString("formatNumeralToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format: in Buchstaben.
        /// </summary>
        internal static string formatTextToolStripMenuItem {
            get {
                return ResourceManager.GetString("formatTextToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ORDNER ZUM SORTIEREN.
        /// </summary>
        internal static string inputFolderLbl {
            get {
                return ResourceManager.GetString("inputFolderLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ursprung:.
        /// </summary>
        internal static string inputPathLbl {
            get {
                return ResourceManager.GetString("inputPathLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wählen Sie einen Ordner zum Sortieren.
        /// </summary>
        internal static string inputSelectionLbl {
            get {
                return ResourceManager.GetString("inputSelectionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Januar.
        /// </summary>
        internal static string january {
            get {
                return ResourceManager.GetString("january", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Juli.
        /// </summary>
        internal static string july {
            get {
                return ResourceManager.GetString("july", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Juni.
        /// </summary>
        internal static string june {
            get {
                return ResourceManager.GetString("june", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deutsch.
        /// </summary>
        internal static string LangName {
            get {
                return ResourceManager.GetString("LangName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sprache:.
        /// </summary>
        internal static string languageLbl {
            get {
                return ResourceManager.GetString("languageLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à März.
        /// </summary>
        internal static string march {
            get {
                return ResourceManager.GetString("march", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mai.
        /// </summary>
        internal static string may {
            get {
                return ResourceManager.GetString("may", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monat.
        /// </summary>
        internal static string monthChk {
            get {
                return ResourceManager.GetString("monthChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nein.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à November.
        /// </summary>
        internal static string november {
            get {
                return ResourceManager.GetString("november", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Digital.
        /// </summary>
        internal static string numeralFormatChk {
            get {
                return ResourceManager.GetString("numeralFormatChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oktober.
        /// </summary>
        internal static string october {
            get {
                return ResourceManager.GetString("october", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Optionen.
        /// </summary>
        internal static string optionsBtn {
            get {
                return ResourceManager.GetString("optionsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Optionen.
        /// </summary>
        internal static string optionsLbl {
            get {
                return ResourceManager.GetString("optionsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ZIELORDNER.
        /// </summary>
        internal static string outputDirectoryLbl {
            get {
                return ResourceManager.GetString("outputDirectoryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ziel:.
        /// </summary>
        internal static string outputPathLbl {
            get {
                return ResourceManager.GetString("outputPathLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wählen Sie einen Zielordner.
        /// </summary>
        internal static string outputSelectionLbl {
            get {
                return ResourceManager.GetString("outputSelectionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dateisortierung vorbereiten....
        /// </summary>
        internal static string preparingFileSorting {
            get {
                return ResourceManager.GetString("preparingFileSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verarbeitung:.
        /// </summary>
        internal static string processingLbl {
            get {
                return ResourceManager.GetString("processingLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Progression:.
        /// </summary>
        internal static string progressionLbl {
            get {
                return ResourceManager.GetString("progressionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vorhandene Dateien lesen....
        /// </summary>
        internal static string readingExistingFiles {
            get {
                return ResourceManager.GetString("readingExistingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Möchten Sie die Operation wirklich unterbrechen?.
        /// </summary>
        internal static string reallyWantToInterrupt {
            get {
                return ResourceManager.GetString("reallyWantToInterrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erinnere mich an meine Wahl für alle Dateien..
        /// </summary>
        internal static string remindMyChoiceForAllFiles {
            get {
                return ResourceManager.GetString("remindMyChoiceForAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bitte geben Sie ein Verzeichnis zum Sortieren an..
        /// </summary>
        internal static string selectInputDirectory {
            get {
                return ResourceManager.GetString("selectInputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bitte geben Sie ein Verzeichnis an, in das die sortierten Dateien platziert werden sollen..
        /// </summary>
        internal static string selectOutputDirectory {
            get {
                return ResourceManager.GetString("selectOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à September.
        /// </summary>
        internal static string september {
            get {
                return ResourceManager.GetString("september", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sortierschema.
        /// </summary>
        internal static string sortGroupBox {
            get {
                return ResourceManager.GetString("sortGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sortierung....
        /// </summary>
        internal static string sortingLbl {
            get {
                return ResourceManager.GetString("sortingLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  START.
        /// </summary>
        internal static string startBtn {
            get {
                return ResourceManager.GetString("startBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erfolg.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In Briefen.
        /// </summary>
        internal static string textFormatChk {
            get {
                return ResourceManager.GetString("textFormatChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dateisortierung wurde abgebrochen..
        /// </summary>
        internal static string workCancelled {
            get {
                return ResourceManager.GetString("workCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jahr.
        /// </summary>
        internal static string yearChk {
            get {
                return ResourceManager.GetString("yearChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ja.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ihre Fotos.
        /// </summary>
        internal static string yourPicturesLbl {
            get {
                return ResourceManager.GetString("yourPicturesLbl", resourceCulture);
            }
        }
    }
}
