//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPicSorter.Lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_fr() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPicSorter.Lang.Lang-fr", typeof(Lang_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  À propos.
        /// </summary>
        internal static string aboutBtn {
            get {
                return ResourceManager.GetString("aboutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un fichier nommé.
        /// </summary>
        internal static string aFileNamed {
            get {
                return ResourceManager.GetString("aFileNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à existe déjà. Voulez-vous le remplacer ? Sélectionnez Non pour garder les deux fichiers..
        /// </summary>
        internal static string alreadyExistsReplaceIt {
            get {
                return ResourceManager.GetString("alreadyExistsReplaceIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Souhaitez-vous toujours remplacer les fichiers déjà existants ?.
        /// </summary>
        internal static string alwaysOverwrite {
            get {
                return ResourceManager.GetString("alwaysOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Souhaitez-vous toujours garder les fichiers ayant le même nom ?.
        /// </summary>
        internal static string alwaysRename {
            get {
                return ResourceManager.GetString("alwaysRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à avril.
        /// </summary>
        internal static string april {
            get {
                return ResourceManager.GetString("april", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention.
        /// </summary>
        internal static string attention {
            get {
                return ResourceManager.GetString("attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à août.
        /// </summary>
        internal static string august {
            get {
                return ResourceManager.GetString("august", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parcourir....
        /// </summary>
        internal static string browseBtn {
            get {
                return ResourceManager.GetString("browseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annulation.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string cancelBtn {
            get {
                return ResourceManager.GetString("cancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annulation en cours. Veuillez patienter..
        /// </summary>
        internal static string cancellationInProgress {
            get {
                return ResourceManager.GetString("cancellationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annulation....
        /// </summary>
        internal static string cancellingBtn {
            get {
                return ResourceManager.GetString("cancellingBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copie des fichiers....
        /// </summary>
        internal static string copyingFiles {
            get {
                return ResourceManager.GetString("copyingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à n&apos;a pas pu être copié..
        /// </summary>
        internal static string couldNotBeCopied {
            get {
                return ResourceManager.GetString("couldNotBeCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à n&apos;a pas pu être remplacé..
        /// </summary>
        internal static string couldNotBeReplaced {
            get {
                return ResourceManager.GetString("couldNotBeReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format de la date :.
        /// </summary>
        internal static string dateFormatLbl {
            get {
                return ResourceManager.GetString("dateFormatLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jour.
        /// </summary>
        internal static string dayChk {
            get {
                return ResourceManager.GetString("dayChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à décembre.
        /// </summary>
        internal static string december {
            get {
                return ResourceManager.GetString("december", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails :.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chercher les doublons pendant le tri.
        /// </summary>
        internal static string duplicateChk {
            get {
                return ResourceManager.GetString("duplicateChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue pendant le tri des fichiers..
        /// </summary>
        internal static string errorOccured {
            get {
                return ResourceManager.GetString("errorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exemple :.
        /// </summary>
        internal static string exampleLbl {
            get {
                return ResourceManager.GetString("exampleLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à février.
        /// </summary>
        internal static string february {
            get {
                return ResourceManager.GetString("february", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos fichiers ont été triés..
        /// </summary>
        internal static string fileSorted {
            get {
                return ResourceManager.GetString("fileSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finalisation....
        /// </summary>
        internal static string finalizing {
            get {
                return ResourceManager.GetString("finalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format : numérique.
        /// </summary>
        internal static string formatNumeralToolStripMenuItem {
            get {
                return ResourceManager.GetString("formatNumeralToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format : en lettres.
        /// </summary>
        internal static string formatTextToolStripMenuItem {
            get {
                return ResourceManager.GetString("formatTextToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DOSSIER À TRIER.
        /// </summary>
        internal static string inputFolderLbl {
            get {
                return ResourceManager.GetString("inputFolderLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Origine :.
        /// </summary>
        internal static string inputPathLbl {
            get {
                return ResourceManager.GetString("inputPathLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionnez un dossier à trier.
        /// </summary>
        internal static string inputSelectionLbl {
            get {
                return ResourceManager.GetString("inputSelectionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à janvier.
        /// </summary>
        internal static string january {
            get {
                return ResourceManager.GetString("january", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à juillet.
        /// </summary>
        internal static string july {
            get {
                return ResourceManager.GetString("july", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à juin.
        /// </summary>
        internal static string june {
            get {
                return ResourceManager.GetString("june", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        internal static string LangName {
            get {
                return ResourceManager.GetString("LangName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue :.
        /// </summary>
        internal static string languageLbl {
            get {
                return ResourceManager.GetString("languageLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mars.
        /// </summary>
        internal static string march {
            get {
                return ResourceManager.GetString("march", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mai.
        /// </summary>
        internal static string may {
            get {
                return ResourceManager.GetString("may", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mois.
        /// </summary>
        internal static string monthChk {
            get {
                return ResourceManager.GetString("monthChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à novembre.
        /// </summary>
        internal static string november {
            get {
                return ResourceManager.GetString("november", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numérique.
        /// </summary>
        internal static string numeralFormatChk {
            get {
                return ResourceManager.GetString("numeralFormatChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à octobre.
        /// </summary>
        internal static string october {
            get {
                return ResourceManager.GetString("october", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Options.
        /// </summary>
        internal static string optionsBtn {
            get {
                return ResourceManager.GetString("optionsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        internal static string optionsLbl {
            get {
                return ResourceManager.GetString("optionsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DOSSIER DE DESTINATION.
        /// </summary>
        internal static string outputDirectoryLbl {
            get {
                return ResourceManager.GetString("outputDirectoryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination :.
        /// </summary>
        internal static string outputPathLbl {
            get {
                return ResourceManager.GetString("outputPathLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionnez un dossier de destination.
        /// </summary>
        internal static string outputSelectionLbl {
            get {
                return ResourceManager.GetString("outputSelectionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Préparation du tri des fichiers....
        /// </summary>
        internal static string preparingFileSorting {
            get {
                return ResourceManager.GetString("preparingFileSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Traitement :.
        /// </summary>
        internal static string processingLbl {
            get {
                return ResourceManager.GetString("processingLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Progression :.
        /// </summary>
        internal static string progressionLbl {
            get {
                return ResourceManager.GetString("progressionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lecture des fichiers existants....
        /// </summary>
        internal static string readingExistingFiles {
            get {
                return ResourceManager.GetString("readingExistingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Souhaitez-vous vous vraiment interrompre l&apos;opération ?.
        /// </summary>
        internal static string reallyWantToInterrupt {
            get {
                return ResourceManager.GetString("reallyWantToInterrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se souvenir de mon choix pour tous les fichiers.
        /// </summary>
        internal static string remindMyChoiceForAllFiles {
            get {
                return ResourceManager.GetString("remindMyChoiceForAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez indiquer un dossier à trier..
        /// </summary>
        internal static string selectInputDirectory {
            get {
                return ResourceManager.GetString("selectInputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez indiquer un répertoire dans lequel placer les fichiers triés..
        /// </summary>
        internal static string selectOutputDirectory {
            get {
                return ResourceManager.GetString("selectOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à septembre.
        /// </summary>
        internal static string september {
            get {
                return ResourceManager.GetString("september", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Schéma de tri.
        /// </summary>
        internal static string sortGroupBox {
            get {
                return ResourceManager.GetString("sortGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tri en cours....
        /// </summary>
        internal static string sortingLbl {
            get {
                return ResourceManager.GetString("sortingLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  DÉMARRER.
        /// </summary>
        internal static string startBtn {
            get {
                return ResourceManager.GetString("startBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opération terminée.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En lettres.
        /// </summary>
        internal static string textFormatChk {
            get {
                return ResourceManager.GetString("textFormatChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le tri des fichiers a été annulé..
        /// </summary>
        internal static string workCancelled {
            get {
                return ResourceManager.GetString("workCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Année.
        /// </summary>
        internal static string yearChk {
            get {
                return ResourceManager.GetString("yearChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos photos.
        /// </summary>
        internal static string yourPicturesLbl {
            get {
                return ResourceManager.GetString("yourPicturesLbl", resourceCulture);
            }
        }
    }
}
