//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPicSorter.Lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_en() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPicSorter.Lang.Lang-en", typeof(Lang_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  About.
        /// </summary>
        internal static string aboutBtn {
            get {
                return ResourceManager.GetString("aboutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A file named.
        /// </summary>
        internal static string aFileNamed {
            get {
                return ResourceManager.GetString("aFileNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à already exists. Do you want to replace it? Select No to keep both..
        /// </summary>
        internal static string alreadyExistsReplaceIt {
            get {
                return ResourceManager.GetString("alreadyExistsReplaceIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you always want to replace files that already exist?.
        /// </summary>
        internal static string alwaysOverwrite {
            get {
                return ResourceManager.GetString("alwaysOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you always want to keep files that have the same name?.
        /// </summary>
        internal static string alwaysRename {
            get {
                return ResourceManager.GetString("alwaysRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à april.
        /// </summary>
        internal static string april {
            get {
                return ResourceManager.GetString("april", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention.
        /// </summary>
        internal static string attention {
            get {
                return ResourceManager.GetString("attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à august.
        /// </summary>
        internal static string august {
            get {
                return ResourceManager.GetString("august", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse....
        /// </summary>
        internal static string browseBtn {
            get {
                return ResourceManager.GetString("browseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string cancelBtn {
            get {
                return ResourceManager.GetString("cancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancellation in progress. Please wait..
        /// </summary>
        internal static string cancellationInProgress {
            get {
                return ResourceManager.GetString("cancellationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancelling....
        /// </summary>
        internal static string cancellingBtn {
            get {
                return ResourceManager.GetString("cancellingBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copying files....
        /// </summary>
        internal static string copyingFiles {
            get {
                return ResourceManager.GetString("copyingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à could not be copied..
        /// </summary>
        internal static string couldNotBeCopied {
            get {
                return ResourceManager.GetString("couldNotBeCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à could not be replaced..
        /// </summary>
        internal static string couldNotBeReplaced {
            get {
                return ResourceManager.GetString("couldNotBeReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date format:.
        /// </summary>
        internal static string dateFormatLbl {
            get {
                return ResourceManager.GetString("dateFormatLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Day.
        /// </summary>
        internal static string dayChk {
            get {
                return ResourceManager.GetString("dayChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à december.
        /// </summary>
        internal static string december {
            get {
                return ResourceManager.GetString("december", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details:.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Look for duplicates while sorting.
        /// </summary>
        internal static string duplicateChk {
            get {
                return ResourceManager.GetString("duplicateChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured during file sorting..
        /// </summary>
        internal static string errorOccured {
            get {
                return ResourceManager.GetString("errorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Example:.
        /// </summary>
        internal static string exampleLbl {
            get {
                return ResourceManager.GetString("exampleLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à february.
        /// </summary>
        internal static string february {
            get {
                return ResourceManager.GetString("february", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your files have been sorted..
        /// </summary>
        internal static string fileSorted {
            get {
                return ResourceManager.GetString("fileSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finalizing....
        /// </summary>
        internal static string finalizing {
            get {
                return ResourceManager.GetString("finalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format: numeral.
        /// </summary>
        internal static string formatNumeralToolStripMenuItem {
            get {
                return ResourceManager.GetString("formatNumeralToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format: text.
        /// </summary>
        internal static string formatTextToolStripMenuItem {
            get {
                return ResourceManager.GetString("formatTextToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INPUT FOLDER.
        /// </summary>
        internal static string inputFolderLbl {
            get {
                return ResourceManager.GetString("inputFolderLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input:.
        /// </summary>
        internal static string inputPathLbl {
            get {
                return ResourceManager.GetString("inputPathLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a folder to sort.
        /// </summary>
        internal static string inputSelectionLbl {
            get {
                return ResourceManager.GetString("inputSelectionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à january.
        /// </summary>
        internal static string january {
            get {
                return ResourceManager.GetString("january", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à july.
        /// </summary>
        internal static string july {
            get {
                return ResourceManager.GetString("july", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à june.
        /// </summary>
        internal static string june {
            get {
                return ResourceManager.GetString("june", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string LangName {
            get {
                return ResourceManager.GetString("LangName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language:.
        /// </summary>
        internal static string languageLbl {
            get {
                return ResourceManager.GetString("languageLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à march.
        /// </summary>
        internal static string march {
            get {
                return ResourceManager.GetString("march", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à may.
        /// </summary>
        internal static string may {
            get {
                return ResourceManager.GetString("may", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Month.
        /// </summary>
        internal static string monthChk {
            get {
                return ResourceManager.GetString("monthChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à november.
        /// </summary>
        internal static string november {
            get {
                return ResourceManager.GetString("november", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numeral.
        /// </summary>
        internal static string numeralFormatChk {
            get {
                return ResourceManager.GetString("numeralFormatChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à october.
        /// </summary>
        internal static string october {
            get {
                return ResourceManager.GetString("october", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Options.
        /// </summary>
        internal static string optionsBtn {
            get {
                return ResourceManager.GetString("optionsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        internal static string optionsLbl {
            get {
                return ResourceManager.GetString("optionsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OUTPUT DIRECTORY.
        /// </summary>
        internal static string outputDirectoryLbl {
            get {
                return ResourceManager.GetString("outputDirectoryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Output:.
        /// </summary>
        internal static string outputPathLbl {
            get {
                return ResourceManager.GetString("outputPathLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a destination directory.
        /// </summary>
        internal static string outputSelectionLbl {
            get {
                return ResourceManager.GetString("outputSelectionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preparing file sorting....
        /// </summary>
        internal static string preparingFileSorting {
            get {
                return ResourceManager.GetString("preparingFileSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Processing:.
        /// </summary>
        internal static string processingLbl {
            get {
                return ResourceManager.GetString("processingLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Progression:.
        /// </summary>
        internal static string progressionLbl {
            get {
                return ResourceManager.GetString("progressionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading existing files....
        /// </summary>
        internal static string readingExistingFiles {
            get {
                return ResourceManager.GetString("readingExistingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you really want to interrupt the operation?.
        /// </summary>
        internal static string reallyWantToInterrupt {
            get {
                return ResourceManager.GetString("reallyWantToInterrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remind my choice for all files.
        /// </summary>
        internal static string remindMyChoiceForAllFiles {
            get {
                return ResourceManager.GetString("remindMyChoiceForAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a directory to sort..
        /// </summary>
        internal static string selectInputDirectory {
            get {
                return ResourceManager.GetString("selectInputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a directory to output the sorted files..
        /// </summary>
        internal static string selectOutputDirectory {
            get {
                return ResourceManager.GetString("selectOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à september.
        /// </summary>
        internal static string september {
            get {
                return ResourceManager.GetString("september", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort pattern.
        /// </summary>
        internal static string sortGroupBox {
            get {
                return ResourceManager.GetString("sortGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorting....
        /// </summary>
        internal static string sortingLbl {
            get {
                return ResourceManager.GetString("sortingLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  START.
        /// </summary>
        internal static string startBtn {
            get {
                return ResourceManager.GetString("startBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text.
        /// </summary>
        internal static string textFormatChk {
            get {
                return ResourceManager.GetString("textFormatChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File sorting was cancelled..
        /// </summary>
        internal static string workCancelled {
            get {
                return ResourceManager.GetString("workCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Year.
        /// </summary>
        internal static string yearChk {
            get {
                return ResourceManager.GetString("yearChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your pictures.
        /// </summary>
        internal static string yourPicturesLbl {
            get {
                return ResourceManager.GetString("yourPicturesLbl", resourceCulture);
            }
        }
    }
}
